version: '3.7'

volumes:
  db_blog:

services:
  blog-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: blog_api
    depends_on:
      - db-blog-api
    ports:
      - 3000:3000
    restart: always
  db-blog-api:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - db_blog:/var/lib/postgresql/data
    restart: always
    expose:
      - 5432
  mongodb:
    image: mongo
    container_name: mongodb
    environment:
      MONGO_INITDB_DATABASE: ${DB_NAME}
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
    expose:
      - 27017