version: '3.7'

volumes:
  db_blog:

services:
  blog-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: blog_api
    depends_on:
      - db-blog-api
    ports:
      - 3000:3000
    restart: always
  db-blog-api:
    image: mongo
    environment:
        MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
        MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
        MONGO_INITDB_DATABASE: ${DB_NAME}
    volumes:
      - db_blog:/data/db
    restart: always
    expose:
      - 27017
    ports:
      - "27017:27017"
